const windows=[[0,3,.5688,'Fatigue Detected'],[3,6,.2579,'Alert / Normal'],[6,9,.5247,'Fatigue Detected'],[9,12,.3041,'Alert / Normal'],[12,15,.2789,'Alert / Normal'],[15,18,.4229,'Monitor'],[18,21,.4033,'Monitor'],[21,24,.2918,'Alert / Normal'],[24,27,.4829,'Monitor'],[27,30,.4385,'Monitor'],[30,33,.9575,'High Fatigue Risk'],[33,36,.7971,'High Fatigue Risk'],[36,39,.8272,'High Fatigue Risk'],[39,42,.6856,'Fatigue Detected'],[42,45,.8356,'High Fatigue Risk'],[45,48,.7047,'Fatigue Detected'],[48,51,.5702,'Fatigue Detected'],[51,54,.8245,'High Fatigue Risk'],[54,57,.8049,'High Fatigue Risk'],[57,60,.7779,'High Fatigue Risk']];
const canvas=document.getElementById('eegCanvas'),ctx=canvas.getContext('2d'),predictionCanvas=document.getElementById('predictionCanvas'),pctx=predictionCanvas.getContext('2d');
const statusBox=document.getElementById('demoStatus'),statusText=statusBox.querySelector('b'),statusDetail=statusBox.querySelector('p'),timeEl=document.getElementById('demoTime'),progress=document.getElementById('timelineProgress'),start=document.getElementById('startDemo'),stop=document.getElementById('stopDemo'),alertBox=document.getElementById('emergencyAlert'),rangeEl=document.getElementById('windowRange'),probabilityEl=document.getElementById('windowProbability');
document.getElementById('channelLabels').innerHTML=['Fp1','Fp2','F3','F4','C3','C4','O1','O2'].map(x=>`<span>${x}</span>`).join('');let running=false,alarming=false,startedAt=0,animation,audioContext,oscillator,gain,activeIndex=-1;
const colorFor=w=>w[3]==='High Fatigue Risk'?'#df6556':w[3]==='Fatigue Detected'?'#e5a23c':'#45b889';
function drawPrediction(index=-1){const w=predictionCanvas.width,h=predictionCanvas.height,pad=26;pctx.clearRect(0,0,w,h);[0,.5,1].forEach(v=>{const y=h-pad-v*(h-pad*2);pctx.strokeStyle='#e8efea';pctx.beginPath();pctx.moveTo(pad,y);pctx.lineTo(w-pad,y);pctx.stroke();pctx.fillStyle='#8b9790';pctx.font='10px DM Mono';pctx.fillText(`${Math.round(v*100)}%`,1,y+3)});const gap=5,bw=(w-pad*2-gap*(windows.length-1))/windows.length;windows.forEach((win,i)=>{const x=pad+i*(bw+gap),barH=win[2]*(h-pad*2),y=h-pad-barH;pctx.fillStyle=colorFor(win);pctx.globalAlpha=i===index?1:.62;pctx.fillRect(x,y,bw,barH);if(i===index){pctx.strokeStyle='#18251f';pctx.lineWidth=2;pctx.strokeRect(x-1,y-1,bw+2,barH+2)}});pctx.globalAlpha=1;pctx.fillStyle='#819088';pctx.font='10px DM Mono';pctx.fillText('0s',pad,h-5);pctx.fillText('60s',w-pad-18,h-5)}
function draw(now=0){const w=canvas.width,h=canvas.height,step=h/8;ctx.fillStyle='#10211b';ctx.fillRect(0,0,w,h);ctx.strokeStyle='#234338';ctx.lineWidth=1;for(let i=0;i<8;i++){const y=step*i+step/2;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y);ctx.stroke()}const elapsed=running?(performance.now()-startedAt)/1000:0,index=Math.min(19,Math.floor(elapsed/1.5)),strength=index>=10?.95:windows[index]?.[2]||.18;for(let c=0;c<8;c++){ctx.beginPath();ctx.strokeStyle=c%2?'#65dbab':'#82d4ed';ctx.lineWidth=1.25;for(let x=0;x<w;x+=4){const t=x/42+now/550+c*.7,wave=Math.sin(t*(2.2+c*.12))*7+Math.sin(t*5.7)*2,load=strength*(Math.sin(t*10+c)*12+Math.sin(t*18)*6),y=step*c+step/2+wave+load;x?ctx.lineTo(x,y):ctx.moveTo(x,y)}ctx.stroke()}if(running){updateState(elapsed,index);if(running)animation=requestAnimationFrame(draw)}}
function updateState(sec,index){const win=windows[index];if(index!==activeIndex){activeIndex=index;rangeEl.textContent=`${win[0]}s – ${win[1]}s`;probabilityEl.textContent=`${Math.round(win[2]*100)}% · ${win[3]}`;probabilityEl.style.color=colorFor(win);drawPrediction(index);if(win[2]>=.5)triggerAlert(win);else stopAlert(false)}progress.style.width=`${Math.min(100,sec/30*100)}%`;progress.style.background=colorFor(win);timeEl.textContent=`00:${String(Math.min(30,Math.floor(sec))).padStart(2,'0')}`;if(sec>=30)finishDemo()}
function startAlarm(){audioContext=new(window.AudioContext||window.webkitAudioContext)();oscillator=audioContext.createOscillator();gain=audioContext.createGain();oscillator.type='square';oscillator.frequency.value=820;gain.gain.value=.055;oscillator.connect(gain).connect(audioContext.destination);oscillator.start()}
function silenceAlarm(){if(oscillator){oscillator.stop();oscillator.disconnect();oscillator=null}if(audioContext){audioContext.close();audioContext=null}}
function triggerAlert(win){if(alarming)return;alarming=true;startAlarm();stop.disabled=false;statusBox.className='demo-status alerting';statusText.textContent='Fatigue detected — alarm active';statusDetail.textContent=`${Math.round(win[2]*100)}% probability in the current detection window. Emergency contacts notified.`;alertBox.classList.add('show')}
function stopAlert(manual){if(!alarming)return;alarming=false;silenceAlarm();stop.disabled=true;alertBox.classList.remove('show');statusBox.className='demo-status active';statusText.textContent=manual?'Alarm stopped by user':'Monitoring fatigue level';statusDetail.textContent=manual?'Continue monitoring and follow your personal safety plan.':'No fatigue detected in the current window.'}
function finishDemo(){running=false;cancelAnimationFrame(animation);stopAlert(false);start.disabled=false;start.textContent='▶ Start demo';statusText.textContent='Demo complete';statusDetail.textContent='All supplied prediction windows have been processed.'}
start.addEventListener('click',()=>{if(running)return;running=true;activeIndex=-1;startedAt=performance.now();start.disabled=true;start.textContent='Demo running…';statusBox.className='demo-status active';statusText.textContent='Processing eight EEG channels';statusDetail.textContent='Prediction windows are being processed in real time.';draw()});stop.addEventListener('click',()=>stopAlert(true));document.getElementById('dismissAlert').addEventListener('click',()=>alertBox.classList.remove('show'));drawPrediction();draw();
